# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Apr 20 10:29:17 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1850, 991)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtGui.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(1470, 50, 361, 221))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setObjectName("calendarWidget")
        self.frame1 = QtGui.QFrame(self.centralwidget)
        self.frame1.setGeometry(QtCore.QRect(10, 450, 660, 500))
        self.frame1.setFrameShape(QtGui.QFrame.Panel)
        self.frame1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.graphicsViewSevenOfNineImage = QtGui.QGraphicsView(self.frame1)
        self.graphicsViewSevenOfNineImage.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.graphicsViewSevenOfNineImage.setObjectName("graphicsViewSevenOfNineImage")
        self.frame2 = QtGui.QFrame(self.centralwidget)
        self.frame2.setGeometry(QtCore.QRect(690, 450, 660, 500))
        self.frame2.setFrameShape(QtGui.QFrame.Panel)
        self.frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.graphicsViewDoorImage = QtGui.QGraphicsView(self.frame2)
        self.graphicsViewDoorImage.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.graphicsViewDoorImage.setObjectName("graphicsViewDoorImage")
        self.labelSevenOfNineView = QtGui.QLabel(self.centralwidget)
        self.labelSevenOfNineView.setGeometry(QtCore.QRect(20, 400, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.labelSevenOfNineView.setFont(font)
        self.labelSevenOfNineView.setObjectName("labelSevenOfNineView")
        self.labelDoorView = QtGui.QLabel(self.centralwidget)
        self.labelDoorView.setGeometry(QtCore.QRect(700, 400, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.labelDoorView.setFont(font)
        self.labelDoorView.setObjectName("labelDoorView")
        self.labelLogView = QtGui.QLabel(self.centralwidget)
        self.labelLogView.setGeometry(QtCore.QRect(1370, 400, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setWeight(75)
        font.setBold(True)
        self.labelLogView.setFont(font)
        self.labelLogView.setObjectName("labelLogView")
        self.frame3 = QtGui.QFrame(self.centralwidget)
        self.frame3.setGeometry(QtCore.QRect(1360, 450, 471, 500))
        self.frame3.setFrameShape(QtGui.QFrame.Panel)
        self.frame3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame3.setObjectName("frame3")
        self.textBrowserEventsLog = QtGui.QTextBrowser(self.frame3)
        self.textBrowserEventsLog.setGeometry(QtCore.QRect(10, 10, 451, 481))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowserEventsLog.setFont(font)
        self.textBrowserEventsLog.setObjectName("textBrowserEventsLog")
        self.labelTime = QtGui.QLabel(self.centralwidget)
        self.labelTime.setGeometry(QtCore.QRect(1470, 10, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.labelTime.setFont(font)
        self.labelTime.setAcceptDrops(False)
        self.labelTime.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.labelTime.setObjectName("labelTime")
        self.labelTitle = QtGui.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(740, 10, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 40, 131, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout1 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout1.setObjectName("verticalLayout1")
        self.checkBoxDoorBellStatus = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxDoorBellStatus.setMouseTracking(False)
        self.checkBoxDoorBellStatus.setToolTip("")
        self.checkBoxDoorBellStatus.setCheckable(False)
        self.checkBoxDoorBellStatus.setObjectName("checkBoxDoorBellStatus")
        self.verticalLayout1.addWidget(self.checkBoxDoorBellStatus)
        self.checkBoxDoorOpenerStatus = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxDoorOpenerStatus.setMouseTracking(False)
        self.checkBoxDoorOpenerStatus.setToolTip("")
        self.checkBoxDoorOpenerStatus.setCheckable(True)
        self.checkBoxDoorOpenerStatus.setChecked(True)
        self.checkBoxDoorOpenerStatus.setObjectName("checkBoxDoorOpenerStatus")
        self.verticalLayout1.addWidget(self.checkBoxDoorOpenerStatus)
        self.checkBoxEnvironmentStatus = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxEnvironmentStatus.setMouseTracking(False)
        self.checkBoxEnvironmentStatus.setToolTip("")
        self.checkBoxEnvironmentStatus.setCheckable(False)
        self.checkBoxEnvironmentStatus.setObjectName("checkBoxEnvironmentStatus")
        self.verticalLayout1.addWidget(self.checkBoxEnvironmentStatus)
        self.checkBoxLightingStatus = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxLightingStatus.setMouseTracking(False)
        self.checkBoxLightingStatus.setToolTip("")
        self.checkBoxLightingStatus.setCheckable(False)
        self.checkBoxLightingStatus.setObjectName("checkBoxLightingStatus")
        self.verticalLayout1.addWidget(self.checkBoxLightingStatus)
        self.checkBoxAppliancesStatus = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxAppliancesStatus.setMouseTracking(False)
        self.checkBoxAppliancesStatus.setToolTip("")
        self.checkBoxAppliancesStatus.setCheckable(False)
        self.checkBoxAppliancesStatus.setObjectName("checkBoxAppliancesStatus")
        self.verticalLayout1.addWidget(self.checkBoxAppliancesStatus)
        self.checkBoxAlarmsStatus = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxAlarmsStatus.setMouseTracking(False)
        self.checkBoxAlarmsStatus.setToolTip("")
        self.checkBoxAlarmsStatus.setCheckable(False)
        self.checkBoxAlarmsStatus.setObjectName("checkBoxAlarmsStatus")
        self.verticalLayout1.addWidget(self.checkBoxAlarmsStatus)
        self.checkBoxCloudConnectionStatus = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBoxCloudConnectionStatus.setMouseTracking(False)
        self.checkBoxCloudConnectionStatus.setToolTip("")
        self.checkBoxCloudConnectionStatus.setCheckable(False)
        self.checkBoxCloudConnectionStatus.setObjectName("checkBoxCloudConnectionStatus")
        self.verticalLayout1.addWidget(self.checkBoxCloudConnectionStatus)
        self.frameToolButtons = QtGui.QFrame(self.centralwidget)
        self.frameToolButtons.setGeometry(QtCore.QRect(20, 350, 1811, 41))
        self.frameToolButtons.setFrameShape(QtGui.QFrame.Panel)
        self.frameToolButtons.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameToolButtons.setObjectName("frameToolButtons")
        self.toolButtonOpenDoor = QtGui.QToolButton(self.frameToolButtons)
        self.toolButtonOpenDoor.setGeometry(QtCore.QRect(10, 10, 111, 22))
        self.toolButtonOpenDoor.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButtonOpenDoor.setObjectName("toolButtonOpenDoor")
        self.toolButtonResetLog = QtGui.QToolButton(self.frameToolButtons)
        self.toolButtonResetLog.setGeometry(QtCore.QRect(250, 10, 111, 22))
        self.toolButtonResetLog.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButtonResetLog.setObjectName("toolButtonResetLog")
        self.toolButtonNodesHealth = QtGui.QToolButton(self.frameToolButtons)
        self.toolButtonNodesHealth.setGeometry(QtCore.QRect(130, 10, 111, 22))
        self.toolButtonNodesHealth.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButtonNodesHealth.setObjectName("toolButtonNodesHealth")
        self.toolButtonAbout = QtGui.QToolButton(self.frameToolButtons)
        self.toolButtonAbout.setGeometry(QtCore.QRect(1690, 10, 111, 22))
        self.toolButtonAbout.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.toolButtonAbout.setObjectName("toolButtonAbout")
        self.labeltNodeStatus = QtGui.QLabel(self.centralwidget)
        self.labeltNodeStatus.setGeometry(QtCore.QRect(30, 11, 130, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labeltNodeStatus.setFont(font)
        self.labeltNodeStatus.setObjectName("labeltNodeStatus")
        self.frameMessage = QtGui.QFrame(self.centralwidget)
        self.frameMessage.setGeometry(QtCore.QRect(230, 280, 1221, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(246, 250, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 250, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 250, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 250, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 250, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 250, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 250, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 250, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 250, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 250, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.frameMessage.setPalette(palette)
        self.frameMessage.setFrameShape(QtGui.QFrame.Panel)
        self.frameMessage.setFrameShadow(QtGui.QFrame.Sunken)
        self.frameMessage.setLineWidth(5)
        self.frameMessage.setObjectName("frameMessage")
        self.labelRealTimeMessage = QtGui.QLabel(self.frameMessage)
        self.labelRealTimeMessage.setEnabled(True)
        self.labelRealTimeMessage.setGeometry(QtCore.QRect(10, 10, 1201, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(246, 250, 10))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 173, 8))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 250, 10, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.labelRealTimeMessage.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.labelRealTimeMessage.setFont(font)
        self.labelRealTimeMessage.setObjectName("labelRealTimeMessage")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(170, 50, 58, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.labelAlertDoorOpener = QtGui.QLabel(self.centralwidget)
        self.labelAlertDoorOpener.setEnabled(True)
        self.labelAlertDoorOpener.setGeometry(QtCore.QRect(170, 80, 58, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelAlertDoorOpener.setFont(font)
        self.labelAlertDoorOpener.setObjectName("labelAlertDoorOpener")
        self.labelUpTime = QtGui.QLabel(self.centralwidget)
        self.labelUpTime.setGeometry(QtCore.QRect(1520, 280, 301, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(22, 175, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(22, 175, 129))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelUpTime.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelUpTime.setFont(font)
        self.labelUpTime.setObjectName("labelUpTime")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(170, 110, 58, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setEnabled(False)
        self.label_3.setGeometry(QtCore.QRect(170, 140, 58, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(170, 170, 58, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(170, 200, 58, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(170, 230, 58, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSystem = QtGui.QAction(MainWindow)
        self.actionSystem.setObjectName("actionSystem")
        self.actionConsole = QtGui.QAction(MainWindow)
        self.actionConsole.setObjectName("actionConsole")
        self.actionLog = QtGui.QAction(MainWindow)
        self.actionLog.setObjectName("actionLog")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "SuperSmartHome", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSevenOfNineView.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#6b6c6f;\">Seven of Nine View</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDoorView.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#6b6c6f;\">Door View</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelLogView.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#6b6c6f;\">Log</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowserEventsLog.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">All the events are logged in the format</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&lt;Timestamp&gt; - [Event code] Description</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Output is Rich Text html formatted</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTime.setText(QtGui.QApplication.translate("MainWindow", "23:58:17 OTP 5878", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTitle.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600; color:#1358ed;\">Control Center</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxDoorBellStatus.setText(QtGui.QApplication.translate("MainWindow", "Door bell", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxDoorOpenerStatus.setText(QtGui.QApplication.translate("MainWindow", "Door opener", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxEnvironmentStatus.setText(QtGui.QApplication.translate("MainWindow", "Environment", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxLightingStatus.setText(QtGui.QApplication.translate("MainWindow", "Lighting", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAppliancesStatus.setText(QtGui.QApplication.translate("MainWindow", "Appliances", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAlarmsStatus.setText(QtGui.QApplication.translate("MainWindow", "Alarms", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxCloudConnectionStatus.setText(QtGui.QApplication.translate("MainWindow", "Cloud", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonOpenDoor.setText(QtGui.QApplication.translate("MainWindow", "Open Door", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonResetLog.setText(QtGui.QApplication.translate("MainWindow", "Log Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonNodesHealth.setText(QtGui.QApplication.translate("MainWindow", "Nodes Health", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButtonAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.labeltNodeStatus.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">Nodes Status</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRealTimeMessage.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" color:#1358ed;\">Realtime Messages</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#adaeb2;\">ND</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAlertDoorOpener.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#c3000b;\">Alert!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelUpTime.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-style:italic; color:#19c691; vertical-align:sub;\">Running by </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#adaeb2;\">ND</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#adaeb2;\">ND</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#adaeb2;\">ND</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#adaeb2;\">ND</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#adaeb2;\">ND</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSystem.setText(QtGui.QApplication.translate("MainWindow", "System", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConsole.setText(QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLog.setText(QtGui.QApplication.translate("MainWindow", "Log", None, QtGui.QApplication.UnicodeUTF8))

